export const GERICHT= {
    ADD: 'ADD_GERICHT',
    DELETE:"DELETE_GERICHT",
    SELECT:"SELECT_GERICHT",
    DESELECT:"DESELECT_GERICHT",
    UPDATE: "UPDATE_GERICHT",
    LOAD: "LOAD_GERICHTE",
    RESET: "RESET"
}

export const VORSPEISE= {
    ADD: 'ADD_VORSPEISE',
    DELETE:"DELETE_VORSPEISE",
    SELECT:"SELECT_VORSPEISE",
    DESELECT:"DESELECT_VORSPEISE",
    UPDATE: "UPDATE_VORSPEISE",
    LOAD: "LOAD_VORSPEISEN",
    RESET: "RESET"
}

export const BACKWARE= {
    ADD: 'ADD_BACKWARE',
    DELETE:"DELETE_BACKWARE",
    SELECT:"SELECT_BACKWARE",
    DESELECT:"DESELECT_BACKWARE",
    UPDATE: "UPDATE_BACKWARE",
    LOAD: "LOAD_BACKWAREN",
    RESET: "RESET"
}

export const DESSERT= {
    ADD: 'ADD_DESSERT',
    DELETE:"DELETE_DESSERT",
    SELECT:"SELECT_DESSERT",
    DESELECT:"DESELECT_DESSERT",
    UPDATE: "UPDATE_DESSERT",
    LOAD: "LOAD_DESSERTS",
    RESET: "RESET"
}